version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: my_agro_advisor
    restart: always
    environment:
      POSTGRES_USER: veljko
      POSTGRES_PASSWORD: veljkoboss
      POSTGRES_DB: my_agro_advisor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    stop_grace_period: 10s  # Dodaće timeout za zaustavljanje
    # Dodaj i ovo ako problem i dalje postoji
    security_opt:
      - apparmor:unconfined

volumes:
  pgdata:
